export const funnyLines = {
  six: [
    'Absolute cinema! 🎬',
    'What a six into the next colony! 🏡',
    'Galli ka Baap! 👑',
    'Dhoni finishes off in style!',
    'Miyan bade dhingana hai! 🕺',
    'Chakka! Gend real mein gayab! 🎯',
    'Tera Baap aaya! 💪',
    'Street cricket legend! 🔥',
    'Bowling kar ke pachtayega! 😎',
    'SIX! Neighbors calling the police! 🚨',
    'That has gone into orbit! 🛰️',
    'Clean strike! Straight out of the ground!',
    'He has middled that one! Pure timing!',
    'Maximum! Over the ropes in style!',
    'That is massive! Crowd goes wild!',
    'Six of the tournament contender! 🏆',
    'Launch code confirmed! 🚀',
    'Ball has disappeared into the sunset! 🌅',
    'He has tonked that into the car park! 🅿️',
    'That ball is still travelling!',
    'Shot of the day! Take a bow! 🙇',
    'He has smashed that through the line!',
    'Biggest six of the match! 💥',
    'That went so far it needs a passport! 🛂',
    'Towering six! Roof top special!',
    'Stand and deliver! Clean strike!',
    'He has dispatched that into the stands!',
    'Proper six! How good was that!',
    'Gully ka batsman showing his class!',
    'Time to hide the ball! Its gone!',
    'Kya shot hai! Kya timing hai!',
    'Bowler ko pitthu bana diya! 🎯',
    '6 runs! The crowd has gone silent with awe!',
    'What a way to bring up the runs!',
    'That hit has broken a window somewhere!',
  ],
  four: [
    'Shot! Beautifully timed! 👌',
    'Cheeky! 🐐',
    'Mast bro! 🤙',
    'Risky but effective! 😅',
    'Punjabi baazigar! 🏏',
    'Classy shot! 🧐',
    'Tape ball special! 📀',
    'Delicate touch through third man!',
    'Powerful drive down the ground!',
    'Cut away beautifully! Point region!',
    'Swept away fine! Fine leg region!',
    'Classic cover drive! Textbook stuff! 📖',
    'Flick off the pads! So elegant!',
    'Late cut! He has got great wrists!',
    'Slapped through the off side!',
    'Punched off the back foot!',
    'Raced away to the boundary!',
    'Thick edge but it runs away! Lucky! 🍀',
    'Reverse sweep! Innovative and effective!',
    'Dabbed down to third man for four!',
    'Short and wide! Punished!',
    'Overpitched and driven! Easy pickings!',
    'Perfect placement! Gap found! 🎯',
    'Upper cut! Over the keeper!',
    'Inside out over covers! Classy!',
    'Lofted drive! One bounce four!',
    'Scoop shot! Fine leg can only watch!',
    'He is batting on a different surface!',
    'Crunching drive! How clean was that!',
    'Pulled away! No one at deep square!',
    'Flicked through midwicket! Timing!',
    'Thats class written all over it!',
  ],
  wicket: [
    'Bowled! Stumps flying! 🎯',
    'Howzaaaat! 🗣️',
    'Typical gully catch! 🧤',
    'Umpire ka favourite decision! ⚖️',
    'Andar aaya, bahar gaya! 🚪',
    'Saffron army on fire! 🔥',
    'Caught behind! Knew it straight away!',
    'Straight to the fielder! Unlucky! 😬',
    'Leading edge! Simple catch for the bowler!',
    'Stumped! Keeper is quick! 🧤',
    'Run out! Direct hit! 🎯',
    'LBW! Trapped in front! Umpires finger goes up!',
    'Bowl through the gate! Beauty!',
    'Knocked him over! Off stump cartwheeling!',
    'Edged and taken! Slip is safe!',
    'Bowler is on fire! Another one bites the dust!',
    'Thats the breakthrough! Team needed that!',
    'Bowled around the legs! Unplayable!',
    'Caught and bowled! The bowler celebrates!',
    'Timber! Middle stump gone for a walk!',
    'Soft dismissal! Mistimed straight to cover!',
    'Top edge! Easy catch for the keeper!',
    'Big wicket! Game changing moment! ⚡',
    'Swing and a miss! Bowled through the gap!',
    'False shot! Simple catch! Gone!',
  ],
  wide: [
    'Wide! Free run! 🆓',
    'Bowler ko gussa aa raha hai! 😤',
    'Pressure getting to him!',
    'Down the leg side! Called wide!',
    'Too far outside off! Freebie for the batsman!',
    'Spraying it wide! Need to tighten up!',
    'That is way outside the tramline!',
    'Bouner down leg! Easy call for umpire!',
    'Bowler losing his radar completely!',
    'Wide! Extra run and extra ball!',
    'Slipping down leg side again! Frustration!',
    'Line is all over the place!',
  ],
  noBall: [
    'No ball! Free hit loading! 🚀',
    'Overstep! Bad idea! 🚶',
    'Free me run! 🆓',
    'Front foot no ball! The bowler overstepped!',
    'No ball for height! Bouncer above shoulder!',
    'Double bounce! Called a no ball!',
    'Free hit coming up! Danger time for bowler!',
    'Full toss above waist! No ball!',
    'That is illegal! Free runs coming!',
    'Over the wicket no ball! Sloppy!',
    'No ball! Fielding restrictions broken!',
    'Disaster for the bowler! No ball under pressure!',
  ],
  over: [
    'Over complete! Change ends! 🔄',
    'Time for strategic time out! ⏸️',
    'Good over! Only a few runs off it!',
    'Maiden over! Brilliant bowling! 🧹',
    'Expensive over! Bowler taken apart! 💸',
    'Wicket maiden! Dream over! 🌟',
    'Nine runs from the over! Momentum shifting!',
    'Tidy over! Pressure building!',
    'Drinks break! Time to strategize!',
    'Over number {{OVER}}! Halfway there!',
    'That over changed the game!',
  ],
  matchStart: [
    'Match about to begin! Excitement level: 100 💯',
    'Gully ka kohli vs dhoni scene! 🔥',
    'Let the chaos begin! 🏏',
    'Players are ready! Umpires in position!',
    'We are underway! What a beautiful day for cricket!',
    'The stage is set! Let the battle begin!',
    'Toss done! Both teams ready to rumble!',
    'First ball of the match! History in the making!',
    'New match alert! Get your snacks ready! 🍿',
    'Cricket fever is here! Gully style!',
    'The match everyone was waiting for is here!',
    'Game on! May the best team win!',
  ],
  celebration: [
    'What a win! 🏆',
    'Absolutely dominant! 👑',
    'Street cricket supremacy! 💪',
    'Gully champions! 🎉',
    'Mauka mauka! 🫵',
    'They have done it! Incredible victory!',
    'What a performance! Total team effort!',
    'Champions! Take a bow! 🙇',
    'Run away winners! Never in doubt!',
    'Thats how you finish a match!',
    'Clinical performance! The best team won!',
    'Victory belongs to the brave!',
  ],
  hype: [
    'Pressure situation! 😰',
    'Crowd going wild! 🗣️',
    'Kya match hai bhai! 🔥',
    'Edge of the seat stuff! 💺',
    'Turning point loading! ⏳',
    'Can they chase this down?',
    'What a game we have on our hands!',
    'Every run matters now!',
    'This is getting too close to call!',
    'Nail biting finish loading! 💅',
    'The pendulum keeps swinging!',
    'Who wants it more? We are about to find out!',
    'The tension is palpable! You can cut it with a knife!',
    'This is what gully cricket is all about!',
    'Here comes the final over! All to play for!',
    'Game on! Not over until the last ball!',
    'What a contest this has turned into!',
    'Both teams evenly matched! Brilliant stuff!',
    'The crowd senses something special!',
    'Its going down to the wire!',
    'Every single run is being cheered!',
    'Momentum shifting like a pendulum!',
  ],
  manOfMatch: [
    'One-man army!',
    'Match winner!',
    'Gully ka Baap!',
    'Saurav Ganguly of the colony!',
    'Street cricket legend!',
    'Man of the moment! Brilliant performance!',
    'He won it almost single-handedly!',
    'Dominant display! Player of the match!',
    'Star performer! Carried the team!',
    'What a game he has had!',
    'The difference between the two teams!',
    'Match winning knock! Remember the name!',
  ],
  chaos: [
    'Most Chaos Player: runs kamao, wicket do, catch chhodo! 🤪',
    'Chaos ka king! Ek six, ek wicket, ek over-throw!',
    'Complete package: runs se lekar dropped catch tak!',
    'Absolute madlad! Does everything on the field!',
    'Entertainment guaranteed when he is playing!',
    'You never know what he will do next!',
    'Hero to zero to hero again! Rollercoaster!',
    'The definition of chaos cricket!',
    'Both teams best friend and worst enemy!',
    'Plays like its a video game!',
  ],
  dot: [
    'Dot ball! Pressure building! 🫥',
    'Excellent bowling! No room given!',
    'Defended back to the bowler!',
    'Play and miss! Beaten all ends up!',
    'Blocked solidly! Good defense!',
    'Beaten on the outside edge!',
    'Rapped on the pads! Huge appeal turned down!',
    'Perfect yorker! Dug out at the last moment!',
    'Bowled dot! Crowd goes quiet!',
    'No run! Tight bowling continues!',
    'Length ball defended! Maiden building!',
    'Watchful leave! Good judgment!',
    'Cutter does him! Beaten by pace!',
  ],
  runout: [
    'Direct hit and he is gone! 🎯',
    'Run out! What a piece of fielding!',
    'Quick running but not quick enough!',
    'Mix up! Neither wanted to run!',
    'Confusion in the middle! Run out!',
    'Third man collects and throws! Gone!',
    'That was tight! But the batsman is short!',
    'Run out! The fielder has done his homework!',
    'Collapsed mid pitch! Run out!',
  ],
  catch: [
    'Caught! What a grab!',
    'Diving catch! Absolutely brilliant! 🧤',
    'Safe hands! Gone!',
    'Screamer in the deep! One handed! 🤲',
    'Simple catch but pressure situation!',
    'Settled under it! Easy take!',
    'Dropped! Oh no! That was a sitter! 😱',
    'He has shelled it! That could be costly!',
    'Superb catch at midwicket!',
    'Running backwards and takes it!',
  ],
  milestone: [
    'FIFTY! Well played batsman! 🎉',
    'CENTURY! What a knock! 💯',
    'Half century brought up in style!',
    'Hundred! Take a bow! 👏',
    'First fifty of the season! Well deserved!',
    'Quickfire fifty! Run a ball! ⚡',
    'Slow but steady fifty! Anchored the innings!',
    'Maiden century! One to remember!',
  ],
  fifty: [
    'FIFTY! Well played batsman! 🎉',
    'Half century brought up in style!',
    'First fifty of the season! Well deserved!',
    'Quickfire fifty! Run a ball! ⚡',
    'Slow but steady fifty! Anchored the innings!',
    'Fifty up! What a knock this has been!',
    'Captain leads from the front! Fifty!',
  ],
  celebrationRun: [
    'Single! Quick running! 💨',
    'Easy single! Good running between wickets!',
    'They are running like gazelles!',
    'Great running! Turning 1s into 2s! 🏃',
    'They push for the second! And they make it!',
    'Quick single! Sharp running!',
    'Three runs! Excellent running! 🏃‍♂️',
    'They scamper through for a double!',
    'Converted the single into a double!',
  ],
  endMatch: [
    'Match complete! What a game! 🏆',
    'Thats it! All over!',
    'The winning runs have been scored!',
    'Victory! The crowd erupts!',
    'Its all over! What a thriller we had!',
    'Match drawn! Both teams share the honors! 🤝',
    'Super Over needed! Can not separate them! 🔥',
    'End of a cracking match! See you next time!',
  ],
}

export const matchNicknames = [
  'The Gully Classic 🏏',
  'Colony Rivalry 🔥',
  'Terrace Trophy 🏆',
  'Street Fight ⚔️',
  'Tape Ball Wars 💥',
  'Neighborhood Derby 🏡',
  'Concrete Pitch Clash 🧱',
  'Mohalla Showdown 🫵',
  'Rooftop Rumble ☀️',
  'Turf Titans Collide 🌱',
  'The Chappal Chase 🩴',
  'Gully ka World Cup 🌍',
  'Tennis Ball Tussle 🎾',
  'Bhide ka Match 🏠',
  'Colony Super League',
  'The Sunday Banger',
  'Evening Cricket Classic',
  'Night Gully Premier League',
  'Terrace T20 Challenge',
  'Street Cricket Championship',
]

export function getRandomLine(type) {
  const lines = funnyLines[type]
  if (!lines || !lines.length) return '🔥'
  return lines[Math.floor(Math.random() * lines.length)]
}

export function getRandomNickname() {
  return matchNicknames[Math.floor(Math.random() * matchNicknames.length)]
}
